# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/d3-7.4.0" = {
      name = "_at_types_slash_d3";
      packageName = "@types/d3";
      version = "7.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3/-/d3-7.4.0.tgz";
        sha512 = "jIfNVK0ZlxcuRDKtRS/SypEyOQ6UHaFQBKv032X45VvxSJ6Yi5G9behy9h6tNTHTDGh5Vq+KbmBjUWLgY4meCA==";
      };
    };
    "@types/d3-array-3.0.3" = {
      name = "_at_types_slash_d3-array";
      packageName = "@types/d3-array";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-array/-/d3-array-3.0.3.tgz";
        sha512 = "Reoy+pKnvsksN0lQUlcH6dOGjRZ/3WRwXR//m+/8lt1BXeI4xyaUZoqULNjyXXRuh0Mj4LNpkCvhUpQlY3X5xQ==";
      };
    };
    "@types/d3-axis-3.0.1" = {
      name = "_at_types_slash_d3-axis";
      packageName = "@types/d3-axis";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-axis/-/d3-axis-3.0.1.tgz";
        sha512 = "zji/iIbdd49g9WN0aIsGcwcTBUkgLsCSwB+uH+LPVDAiKWENMtI3cJEWt+7/YYwelMoZmbBfzA3qCdrZ2XFNnw==";
      };
    };
    "@types/d3-brush-3.0.1" = {
      name = "_at_types_slash_d3-brush";
      packageName = "@types/d3-brush";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-brush/-/d3-brush-3.0.1.tgz";
        sha512 = "B532DozsiTuQMHu2YChdZU0qsFJSio3Q6jmBYGYNp3gMDzBmuFFgPt9qKA4VYuLZMp4qc6eX7IUFUEsvHiXZAw==";
      };
    };
    "@types/d3-chord-3.0.1" = {
      name = "_at_types_slash_d3-chord";
      packageName = "@types/d3-chord";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-chord/-/d3-chord-3.0.1.tgz";
        sha512 = "eQfcxIHrg7V++W8Qxn6QkqBNBokyhdWSAS73AbkbMzvLQmVVBviknoz2SRS/ZJdIOmhcmmdCRE/NFOm28Z1AMw==";
      };
    };
    "@types/d3-color-3.1.0" = {
      name = "_at_types_slash_d3-color";
      packageName = "@types/d3-color";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-color/-/d3-color-3.1.0.tgz";
        sha512 = "HKuicPHJuvPgCD+np6Se9MQvS6OCbJmOjGvylzMJRlDwUXjKTTXs6Pwgk79O09Vj/ho3u1ofXnhFOaEWWPrlwA==";
      };
    };
    "@types/d3-contour-3.0.1" = {
      name = "_at_types_slash_d3-contour";
      packageName = "@types/d3-contour";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-contour/-/d3-contour-3.0.1.tgz";
        sha512 = "C3zfBrhHZvrpAAK3YXqLWVAGo87A4SvJ83Q/zVJ8rFWJdKejUnDYaWZPkA8K84kb2vDA/g90LTQAz7etXcgoQQ==";
      };
    };
    "@types/d3-delaunay-6.0.1" = {
      name = "_at_types_slash_d3-delaunay";
      packageName = "@types/d3-delaunay";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-delaunay/-/d3-delaunay-6.0.1.tgz";
        sha512 = "tLxQ2sfT0p6sxdG75c6f/ekqxjyYR0+LwPrsO1mbC9YDBzPJhs2HbJJRrn8Ez1DBoHRo2yx7YEATI+8V1nGMnQ==";
      };
    };
    "@types/d3-dispatch-3.0.1" = {
      name = "_at_types_slash_d3-dispatch";
      packageName = "@types/d3-dispatch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-dispatch/-/d3-dispatch-3.0.1.tgz";
        sha512 = "NhxMn3bAkqhjoxabVJWKryhnZXXYYVQxaBnbANu0O94+O/nX9qSjrA1P1jbAQJxJf+VC72TxDX/YJcKue5bRqw==";
      };
    };
    "@types/d3-drag-3.0.1" = {
      name = "_at_types_slash_d3-drag";
      packageName = "@types/d3-drag";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-drag/-/d3-drag-3.0.1.tgz";
        sha512 = "o1Va7bLwwk6h03+nSM8dpaGEYnoIG19P0lKqlic8Un36ymh9NSkNFX1yiXMKNMx8rJ0Kfnn2eovuFaL6Jvj0zA==";
      };
    };
    "@types/d3-dsv-3.0.0" = {
      name = "_at_types_slash_d3-dsv";
      packageName = "@types/d3-dsv";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-dsv/-/d3-dsv-3.0.0.tgz";
        sha512 = "o0/7RlMl9p5n6FQDptuJVMxDf/7EDEv2SYEO/CwdG2tr1hTfUVi0Iavkk2ax+VpaQ/1jVhpnj5rq1nj8vwhn2A==";
      };
    };
    "@types/d3-ease-3.0.0" = {
      name = "_at_types_slash_d3-ease";
      packageName = "@types/d3-ease";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-ease/-/d3-ease-3.0.0.tgz";
        sha512 = "aMo4eaAOijJjA6uU+GIeW018dvy9+oH5Y2VPPzjjfxevvGQ/oRDs+tfYC9b50Q4BygRR8yE2QCLsrT0WtAVseA==";
      };
    };
    "@types/d3-fetch-3.0.1" = {
      name = "_at_types_slash_d3-fetch";
      packageName = "@types/d3-fetch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-fetch/-/d3-fetch-3.0.1.tgz";
        sha512 = "toZJNOwrOIqz7Oh6Q7l2zkaNfXkfR7mFSJvGvlD/Ciq/+SQ39d5gynHJZ/0fjt83ec3WL7+u3ssqIijQtBISsw==";
      };
    };
    "@types/d3-force-3.0.3" = {
      name = "_at_types_slash_d3-force";
      packageName = "@types/d3-force";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-force/-/d3-force-3.0.3.tgz";
        sha512 = "z8GteGVfkWJMKsx6hwC3SiTSLspL98VNpmvLpEFJQpZPq6xpA1I8HNBDNSpukfK0Vb0l64zGFhzunLgEAcBWSA==";
      };
    };
    "@types/d3-format-3.0.1" = {
      name = "_at_types_slash_d3-format";
      packageName = "@types/d3-format";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-format/-/d3-format-3.0.1.tgz";
        sha512 = "5KY70ifCCzorkLuIkDe0Z9YTf9RR2CjBX1iaJG+rgM/cPP+sO+q9YdQ9WdhQcgPj1EQiJ2/0+yUkkziTG6Lubg==";
      };
    };
    "@types/d3-geo-3.0.2" = {
      name = "_at_types_slash_d3-geo";
      packageName = "@types/d3-geo";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-geo/-/d3-geo-3.0.2.tgz";
        sha512 = "DbqK7MLYA8LpyHQfv6Klz0426bQEf7bRTvhMy44sNGVyZoWn//B0c+Qbeg8Osi2Obdc9BLLXYAKpyWege2/7LQ==";
      };
    };
    "@types/d3-hierarchy-3.1.0" = {
      name = "_at_types_slash_d3-hierarchy";
      packageName = "@types/d3-hierarchy";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-hierarchy/-/d3-hierarchy-3.1.0.tgz";
        sha512 = "g+sey7qrCa3UbsQlMZZBOHROkFqx7KZKvUpRzI/tAp/8erZWpYq7FgNKvYwebi2LaEiVs1klhUfd3WCThxmmWQ==";
      };
    };
    "@types/d3-interpolate-3.0.1" = {
      name = "_at_types_slash_d3-interpolate";
      packageName = "@types/d3-interpolate";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-interpolate/-/d3-interpolate-3.0.1.tgz";
        sha512 = "jx5leotSeac3jr0RePOH1KdR9rISG91QIE4Q2PYTu4OymLTZfA3SrnURSLzKH48HmXVUru50b8nje4E79oQSQw==";
      };
    };
    "@types/d3-path-3.0.0" = {
      name = "_at_types_slash_d3-path";
      packageName = "@types/d3-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-path/-/d3-path-3.0.0.tgz";
        sha512 = "0g/A+mZXgFkQxN3HniRDbXMN79K3CdTpLsevj+PXiTcb2hVyvkZUBg37StmgCQkaD84cUJ4uaDAWq7UJOQy2Tg==";
      };
    };
    "@types/d3-polygon-3.0.0" = {
      name = "_at_types_slash_d3-polygon";
      packageName = "@types/d3-polygon";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-polygon/-/d3-polygon-3.0.0.tgz";
        sha512 = "D49z4DyzTKXM0sGKVqiTDTYr+DHg/uxsiWDAkNrwXYuiZVd9o9wXZIo+YsHkifOiyBkmSWlEngHCQme54/hnHw==";
      };
    };
    "@types/d3-quadtree-3.0.2" = {
      name = "_at_types_slash_d3-quadtree";
      packageName = "@types/d3-quadtree";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-quadtree/-/d3-quadtree-3.0.2.tgz";
        sha512 = "QNcK8Jguvc8lU+4OfeNx+qnVy7c0VrDJ+CCVFS9srBo2GL9Y18CnIxBdTF3v38flrGy5s1YggcoAiu6s4fLQIw==";
      };
    };
    "@types/d3-random-3.0.1" = {
      name = "_at_types_slash_d3-random";
      packageName = "@types/d3-random";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-random/-/d3-random-3.0.1.tgz";
        sha512 = "IIE6YTekGczpLYo/HehAy3JGF1ty7+usI97LqraNa8IiDur+L44d0VOjAvFQWJVdZOJHukUJw+ZdZBlgeUsHOQ==";
      };
    };
    "@types/d3-scale-4.0.2" = {
      name = "_at_types_slash_d3-scale";
      packageName = "@types/d3-scale";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-scale/-/d3-scale-4.0.2.tgz";
        sha512 = "Yk4htunhPAwN0XGlIwArRomOjdoBFXC3+kCxK2Ubg7I9shQlVSJy/pG/Ht5ASN+gdMIalpk8TJ5xV74jFsetLA==";
      };
    };
    "@types/d3-scale-chromatic-3.0.0" = {
      name = "_at_types_slash_d3-scale-chromatic";
      packageName = "@types/d3-scale-chromatic";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-scale-chromatic/-/d3-scale-chromatic-3.0.0.tgz";
        sha512 = "dsoJGEIShosKVRBZB0Vo3C8nqSDqVGujJU6tPznsBJxNJNwMF8utmS83nvCBKQYPpjCzaaHcrf66iTRpZosLPw==";
      };
    };
    "@types/d3-selection-3.0.2" = {
      name = "_at_types_slash_d3-selection";
      packageName = "@types/d3-selection";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-selection/-/d3-selection-3.0.2.tgz";
        sha512 = "d29EDd0iUBrRoKhPndhDY6U/PYxOWqgIZwKTooy2UkBfU7TNZNpRho0yLWPxlatQrFWk2mnTu71IZQ4+LRgKlQ==";
      };
    };
    "@types/d3-shape-3.1.0" = {
      name = "_at_types_slash_d3-shape";
      packageName = "@types/d3-shape";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-shape/-/d3-shape-3.1.0.tgz";
        sha512 = "jYIYxFFA9vrJ8Hd4Se83YI6XF+gzDL1aC5DCsldai4XYYiVNdhtpGbA/GM6iyQ8ayhSp3a148LY34hy7A4TxZA==";
      };
    };
    "@types/d3-time-3.0.0" = {
      name = "_at_types_slash_d3-time";
      packageName = "@types/d3-time";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-time/-/d3-time-3.0.0.tgz";
        sha512 = "sZLCdHvBUcNby1cB6Fd3ZBrABbjz3v1Vm90nysCQ6Vt7vd6e/h9Lt7SiJUoEX0l4Dzc7P5llKyhqSi1ycSf1Hg==";
      };
    };
    "@types/d3-time-format-4.0.0" = {
      name = "_at_types_slash_d3-time-format";
      packageName = "@types/d3-time-format";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-time-format/-/d3-time-format-4.0.0.tgz";
        sha512 = "yjfBUe6DJBsDin2BMIulhSHmr5qNR5Pxs17+oW4DoVPyVIXZ+m6bs7j1UVKP08Emv6jRmYrYqxYzO63mQxy1rw==";
      };
    };
    "@types/d3-timer-3.0.0" = {
      name = "_at_types_slash_d3-timer";
      packageName = "@types/d3-timer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-timer/-/d3-timer-3.0.0.tgz";
        sha512 = "HNB/9GHqu7Fo8AQiugyJbv6ZxYz58wef0esl4Mv828w1ZKpAshw/uFWVDUcIB9KKFeFKoxS3cHY07FFgtTRZ1g==";
      };
    };
    "@types/d3-transition-3.0.1" = {
      name = "_at_types_slash_d3-transition";
      packageName = "@types/d3-transition";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-transition/-/d3-transition-3.0.1.tgz";
        sha512 = "Sv4qEI9uq3bnZwlOANvYK853zvpdKEm1yz9rcc8ZTsxvRklcs9Fx4YFuGA3gXoQN/c/1T6QkVNjhaRO/cWj94g==";
      };
    };
    "@types/d3-zoom-3.0.1" = {
      name = "_at_types_slash_d3-zoom";
      packageName = "@types/d3-zoom";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/d3-zoom/-/d3-zoom-3.0.1.tgz";
        sha512 = "7s5L9TjfqIYQmQQEUcpMAcBOahem7TRoSO/+Gkz02GbMVuULiZzjF2BOdw291dbO2aNon4m2OdFsRGaCq2caLQ==";
      };
    };
    "@types/geojson-7946.0.8" = {
      name = "_at_types_slash_geojson";
      packageName = "@types/geojson";
      version = "7946.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/geojson/-/geojson-7946.0.8.tgz";
        sha512 = "1rkryxURpr6aWP7R786/UQOkJ3PcpQiWkAXBmdWc7ryFWqN6a4xfK7BtjXvFBKO9LjQ+MWQSWxYeZX1OApnArA==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "commander-8.3.0" = {
      name = "commander";
      packageName = "commander";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-8.3.0.tgz";
        sha512 = "OkTL9umf+He2DZkUq8f8J9of7yL6RJKI24dVITBmNfZBmri9zYZQrKkuXiKhyfPSu8tUhnVBB1iKXevvnlR4Ww==";
      };
    };
    "d3-7.4.4" = {
      name = "d3";
      packageName = "d3";
      version = "7.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3/-/d3-7.4.4.tgz";
        sha512 = "97FE+MYdAlV3R9P74+R3Uar7wUKkIFu89UWMjEaDhiJ9VxKvqaMxauImy8PC2DdBkdM2BxJOIoLxPrcZUyrKoQ==";
      };
    };
    "d3-array-3.1.6" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-3.1.6.tgz";
        sha512 = "DCbBBNuKOeiR9h04ySRBMW52TFVc91O9wJziuyXw6Ztmy8D3oZbmCkOO3UHKC7ceNJsN2Mavo9+vwV8EAEUXzA==";
      };
    };
    "d3-axis-3.0.0" = {
      name = "d3-axis";
      packageName = "d3-axis";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-axis/-/d3-axis-3.0.0.tgz";
        sha512 = "IH5tgjV4jE/GhHkRV0HiVYPDtvfjHQlQfJHs0usq7M30XcSBvOotpmH1IgkcXsO/5gEQZD43B//fc7SRT5S+xw==";
      };
    };
    "d3-brush-3.0.0" = {
      name = "d3-brush";
      packageName = "d3-brush";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-brush/-/d3-brush-3.0.0.tgz";
        sha512 = "ALnjWlVYkXsVIGlOsuWH1+3udkYFI48Ljihfnh8FZPF2QS9o+PzGLBslO0PjzVoHLZ2KCVgAM8NVkXPJB2aNnQ==";
      };
    };
    "d3-chord-3.0.1" = {
      name = "d3-chord";
      packageName = "d3-chord";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-chord/-/d3-chord-3.0.1.tgz";
        sha512 = "VE5S6TNa+j8msksl7HwjxMHDM2yNK3XCkusIlpX5kwauBfXuyLAtNg9jCp/iHH61tgI4sb6R/EIMWCqEIdjT/g==";
      };
    };
    "d3-color-3.1.0" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-3.1.0.tgz";
        sha512 = "zg/chbXyeBtMQ1LbD/WSoW2DpC3I0mpmPdW+ynRTj/x2DAWYrIY7qeZIHidozwV24m4iavr15lNwIwLxRmOxhA==";
      };
    };
    "d3-contour-3.0.1" = {
      name = "d3-contour";
      packageName = "d3-contour";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-contour/-/d3-contour-3.0.1.tgz";
        sha512 = "0Oc4D0KyhwhM7ZL0RMnfGycLN7hxHB8CMmwZ3+H26PWAG0ozNuYG5hXSDNgmP1SgJkQMrlG6cP20HoaSbvcJTQ==";
      };
    };
    "d3-delaunay-6.0.2" = {
      name = "d3-delaunay";
      packageName = "d3-delaunay";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-delaunay/-/d3-delaunay-6.0.2.tgz";
        sha512 = "IMLNldruDQScrcfT+MWnazhHbDJhcRJyOEBAJfwQnHle1RPh6WDuLvxNArUju2VSMSUuKlY5BGHRJ2cYyoFLQQ==";
      };
    };
    "d3-dispatch-3.0.1" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-3.0.1.tgz";
        sha512 = "rzUyPU/S7rwUflMyLc1ETDeBj0NRuHKKAcvukozwhshr6g6c5d8zh4c2gQjY2bZ0dXeGLWc1PF174P2tVvKhfg==";
      };
    };
    "d3-drag-3.0.0" = {
      name = "d3-drag";
      packageName = "d3-drag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-drag/-/d3-drag-3.0.0.tgz";
        sha512 = "pWbUJLdETVA8lQNJecMxoXfH6x+mO2UQo8rSmZ+QqxcbyA3hfeprFgIT//HW2nlHChWeIIMwS2Fq+gEARkhTkg==";
      };
    };
    "d3-dsv-3.0.1" = {
      name = "d3-dsv";
      packageName = "d3-dsv";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dsv/-/d3-dsv-3.0.1.tgz";
        sha512 = "UG6OvdI5afDIFP9w4G0mNq50dSOsXHJaRE8arAS5o9ApWnIElp8GZw1Dun8vP8OyHOZ/QJUKUJwxiiCCnUwm+Q==";
      };
    };
    "d3-ease-3.0.1" = {
      name = "d3-ease";
      packageName = "d3-ease";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-ease/-/d3-ease-3.0.1.tgz";
        sha512 = "wR/XK3D3XcLIZwpbvQwQ5fK+8Ykds1ip7A2Txe0yxncXSdq1L9skcG7blcedkOX+ZcgxGAmLX1FrRGbADwzi0w==";
      };
    };
    "d3-fetch-3.0.1" = {
      name = "d3-fetch";
      packageName = "d3-fetch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-fetch/-/d3-fetch-3.0.1.tgz";
        sha512 = "kpkQIM20n3oLVBKGg6oHrUchHM3xODkTzjMoj7aWQFq5QEM+R6E4WkzT5+tojDY7yjez8KgCBRoj4aEr99Fdqw==";
      };
    };
    "d3-force-3.0.0" = {
      name = "d3-force";
      packageName = "d3-force";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-force/-/d3-force-3.0.0.tgz";
        sha512 = "zxV/SsA+U4yte8051P4ECydjD/S+qeYtnaIyAs9tgHCqfguma/aAQDjo85A9Z6EKhBirHRJHXIgJUlffT4wdLg==";
      };
    };
    "d3-format-3.1.0" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-3.1.0.tgz";
        sha512 = "YyUI6AEuY/Wpt8KWLgZHsIU86atmikuoOmCfommt0LYHiQSPjvX2AcFc38PX0CBpr2RCyZhjex+NS/LPOv6YqA==";
      };
    };
    "d3-geo-3.0.1" = {
      name = "d3-geo";
      packageName = "d3-geo";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-geo/-/d3-geo-3.0.1.tgz";
        sha512 = "Wt23xBych5tSy9IYAM1FR2rWIBFWa52B/oF/GYe5zbdHrg08FU8+BuI6X4PvTwPDdqdAdq04fuWJpELtsaEjeA==";
      };
    };
    "d3-hierarchy-3.1.2" = {
      name = "d3-hierarchy";
      packageName = "d3-hierarchy";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-hierarchy/-/d3-hierarchy-3.1.2.tgz";
        sha512 = "FX/9frcub54beBdugHjDCdikxThEqjnR93Qt7PvQTOHxyiNCAlvMrHhclk3cD5VeAaq9fxmfRp+CnWw9rEMBuA==";
      };
    };
    "d3-interpolate-3.0.1" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-3.0.1.tgz";
        sha512 = "3bYs1rOD33uo8aqJfKP3JWPAibgw8Zm2+L9vBKEHJ2Rg+viTR7o5Mmv5mZcieN+FRYaAOWX5SJATX6k1PWz72g==";
      };
    };
    "d3-path-3.0.1" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-3.0.1.tgz";
        sha512 = "gq6gZom9AFZby0YLduxT1qmrp4xpBA1YZr19OI717WIdKE2OM5ETq5qrHLb301IgxhLwcuxvGZVLeeWc/k1I6w==";
      };
    };
    "d3-polygon-3.0.1" = {
      name = "d3-polygon";
      packageName = "d3-polygon";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-polygon/-/d3-polygon-3.0.1.tgz";
        sha512 = "3vbA7vXYwfe1SYhED++fPUQlWSYTTGmFmQiany/gdbiWgU/iEyQzyymwL9SkJjFFuCS4902BSzewVGsHHmHtXg==";
      };
    };
    "d3-quadtree-3.0.1" = {
      name = "d3-quadtree";
      packageName = "d3-quadtree";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-quadtree/-/d3-quadtree-3.0.1.tgz";
        sha512 = "04xDrxQTDTCFwP5H6hRhsRcb9xxv2RzkcsygFzmkSIOJy3PeRJP7sNk3VRIbKXcog561P9oU0/rVH6vDROAgUw==";
      };
    };
    "d3-random-3.0.1" = {
      name = "d3-random";
      packageName = "d3-random";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-random/-/d3-random-3.0.1.tgz";
        sha512 = "FXMe9GfxTxqd5D6jFsQ+DJ8BJS4E/fT5mqqdjovykEB2oFbTMDVdg1MGFxfQW+FBOGoB++k8swBrgwSHT1cUXQ==";
      };
    };
    "d3-scale-4.0.2" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-4.0.2.tgz";
        sha512 = "GZW464g1SH7ag3Y7hXjf8RoUuAFIqklOAq3MRl4OaWabTFJY9PN/E1YklhXLh+OQ3fM9yS2nOkCoS+WLZ6kvxQ==";
      };
    };
    "d3-scale-chromatic-3.0.0" = {
      name = "d3-scale-chromatic";
      packageName = "d3-scale-chromatic";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale-chromatic/-/d3-scale-chromatic-3.0.0.tgz";
        sha512 = "Lx9thtxAKrO2Pq6OO2Ua474opeziKr279P/TKZsMAhYyNDD3EnCffdbgeSYN5O7m2ByQsxtuP2CSDczNUIZ22g==";
      };
    };
    "d3-selection-3.0.0" = {
      name = "d3-selection";
      packageName = "d3-selection";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-selection/-/d3-selection-3.0.0.tgz";
        sha512 = "fmTRWbNMmsmWq6xJV8D19U/gw/bwrHfNXxrIN+HfZgnzqTHp9jOmKMhsTUjXOJnZOdZY9Q28y4yebKzqDKlxlQ==";
      };
    };
    "d3-shape-3.1.0" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-3.1.0.tgz";
        sha512 = "tGDh1Muf8kWjEDT/LswZJ8WF85yDZLvVJpYU9Nq+8+yW1Z5enxrmXOhTArlkaElU+CTn0OTVNli+/i+HP45QEQ==";
      };
    };
    "d3-time-3.0.0" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-3.0.0.tgz";
        sha512 = "zmV3lRnlaLI08y9IMRXSDshQb5Nj77smnfpnd2LrBa/2K281Jijactokeak14QacHs/kKq0AQ121nidNYlarbQ==";
      };
    };
    "d3-time-format-4.1.0" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-4.1.0.tgz";
        sha512 = "dJxPBlzC7NugB2PDLwo9Q8JiTR3M3e4/XANkreKSUxF8vvXKqm1Yfq4Q5dl8budlunRVlUUaDUgFt7eA8D6NLg==";
      };
    };
    "d3-timer-3.0.1" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-3.0.1.tgz";
        sha512 = "ndfJ/JxxMd3nw31uyKoY2naivF+r29V+Lc0svZxe1JvvIRmi8hUsrMvdOwgS1o6uBHmiz91geQ0ylPP0aj1VUA==";
      };
    };
    "d3-transition-3.0.1" = {
      name = "d3-transition";
      packageName = "d3-transition";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-transition/-/d3-transition-3.0.1.tgz";
        sha512 = "ApKvfjsSR6tg06xrL434C0WydLr7JewBB3V+/39RMHsaXTOG0zmt/OAXeng5M5LBm0ojmxJrpomQVZ1aPvBL4w==";
      };
    };
    "d3-zoom-3.0.0" = {
      name = "d3-zoom";
      packageName = "d3-zoom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-zoom/-/d3-zoom-3.0.0.tgz";
        sha512 = "b8AmV3kfQaqWAuacbPuNbL6vahnOJflOhexLzMMNLga62+/nh0JzvJ0aO/5a5MVgUFGS7Hu1P9P03o3fJkDCyw==";
      };
    };
    "delaunator-5.0.0" = {
      name = "delaunator";
      packageName = "delaunator";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delaunator/-/delaunator-5.0.0.tgz";
        sha512 = "AyLvtyJdbv/U1GkiS6gUUzclRoAY4Gs75qkMygJJhU75LW4DNuSF2RMzpxs9jw9Oz1BobHjTdkG3zdP55VxAqw==";
      };
    };
    "esbuild-0.14.42" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.14.42.tgz";
        sha512 = "V0uPZotCEHokJdNqyozH6qsaQXqmZEOiZWrXnds/zaH/0SyrIayRXWRB98CENO73MIZ9T3HBIOsmds5twWtmgw==";
      };
    };
    "esbuild-android-64-0.14.42" = {
      name = "esbuild-android-64";
      packageName = "esbuild-android-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-64/-/esbuild-android-64-0.14.42.tgz";
        sha512 = "P4Y36VUtRhK/zivqGVMqhptSrFILAGlYp0Z8r9UQqHJ3iWztRCNWnlBzD9HRx0DbueXikzOiwyOri+ojAFfW6A==";
      };
    };
    "esbuild-android-arm64-0.14.42" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.14.42.tgz";
        sha512 = "0cOqCubq+RWScPqvtQdjXG3Czb3AWI2CaKw3HeXry2eoA2rrPr85HF7IpdU26UWdBXgPYtlTN1LUiuXbboROhg==";
      };
    };
    "esbuild-darwin-64-0.14.42" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.14.42.tgz";
        sha512 = "ipiBdCA3ZjYgRfRLdQwP82rTiv/YVMtW36hTvAN5ZKAIfxBOyPXY7Cejp3bMXWgzKD8B6O+zoMzh01GZsCuEIA==";
      };
    };
    "esbuild-darwin-arm64-0.14.42" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.14.42.tgz";
        sha512 = "bU2tHRqTPOaoH/4m0zYHbFWpiYDmaA0gt90/3BMEFaM0PqVK/a6MA2V/ypV5PO0v8QxN6gH5hBPY4YJ2lopXgA==";
      };
    };
    "esbuild-freebsd-64-0.14.42" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.14.42.tgz";
        sha512 = "75h1+22Ivy07+QvxHyhVqOdekupiTZVLN1PMwCDonAqyXd8TVNJfIRFrdL8QmSJrOJJ5h8H1I9ETyl2L8LQDaw==";
      };
    };
    "esbuild-freebsd-arm64-0.14.42" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.14.42.tgz";
        sha512 = "W6Jebeu5TTDQMJUJVarEzRU9LlKpNkPBbjqSu+GUPTHDCly5zZEQq9uHkmHHl7OKm+mQ2zFySN83nmfCeZCyNA==";
      };
    };
    "esbuild-linux-32-0.14.42" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.14.42.tgz";
        sha512 = "Ooy/Bj+mJ1z4jlWcK5Dl6SlPlCgQB9zg1UrTCeY8XagvuWZ4qGPyYEWGkT94HUsRi2hKsXvcs6ThTOjBaJSMfg==";
      };
    };
    "esbuild-linux-64-0.14.42" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.14.42.tgz";
        sha512 = "2L0HbzQfbTuemUWfVqNIjOfaTRt9zsvjnme6lnr7/MO9toz/MJ5tZhjqrG6uDWDxhsaHI2/nsDgrv8uEEN2eoA==";
      };
    };
    "esbuild-linux-arm-0.14.42" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.14.42.tgz";
        sha512 = "STq69yzCMhdRaWnh29UYrLSr/qaWMm/KqwaRF1pMEK7kDiagaXhSL1zQGXbYv94GuGY/zAwzK98+6idCMUOOCg==";
      };
    };
    "esbuild-linux-arm64-0.14.42" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.14.42.tgz";
        sha512 = "c3Ug3e9JpVr8jAcfbhirtpBauLxzYPpycjWulD71CF6ZSY26tvzmXMJYooQ2YKqDY4e/fPu5K8bm7MiXMnyxuA==";
      };
    };
    "esbuild-linux-mips64le-0.14.42" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.14.42.tgz";
        sha512 = "QuvpHGbYlkyXWf2cGm51LBCHx6eUakjaSrRpUqhPwjh/uvNUYvLmz2LgPTTPwCqaKt0iwL+OGVL0tXA5aDbAbg==";
      };
    };
    "esbuild-linux-ppc64le-0.14.42" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.14.42.tgz";
        sha512 = "8ohIVIWDbDT+i7lCx44YCyIRrOW1MYlks9fxTo0ME2LS/fxxdoJBwHWzaDYhjvf8kNpA+MInZvyOEAGoVDrMHg==";
      };
    };
    "esbuild-linux-riscv64-0.14.42" = {
      name = "esbuild-linux-riscv64";
      packageName = "esbuild-linux-riscv64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-riscv64/-/esbuild-linux-riscv64-0.14.42.tgz";
        sha512 = "DzDqK3TuoXktPyG1Lwx7vhaF49Onv3eR61KwQyxYo4y5UKTpL3NmuarHSIaSVlTFDDpcIajCDwz5/uwKLLgKiQ==";
      };
    };
    "esbuild-linux-s390x-0.14.42" = {
      name = "esbuild-linux-s390x";
      packageName = "esbuild-linux-s390x";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-s390x/-/esbuild-linux-s390x-0.14.42.tgz";
        sha512 = "YFRhPCxl8nb//Wn6SiS5pmtplBi4z9yC2gLrYoYI/tvwuB1jldir9r7JwAGy1Ck4D7sE7wBN9GFtUUX/DLdcEQ==";
      };
    };
    "esbuild-netbsd-64-0.14.42" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.14.42.tgz";
        sha512 = "QYSD2k+oT9dqB/4eEM9c+7KyNYsIPgzYOSrmfNGDIyJrbT1d+CFVKvnKahDKNJLfOYj8N4MgyFaU9/Ytc6w5Vw==";
      };
    };
    "esbuild-openbsd-64-0.14.42" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.14.42.tgz";
        sha512 = "M2meNVIKWsm2HMY7+TU9AxM7ZVwI9havdsw6m/6EzdXysyCFFSoaTQ/Jg03izjCsK17FsVRHqRe26Llj6x0MNA==";
      };
    };
    "esbuild-sunos-64-0.14.42" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.14.42.tgz";
        sha512 = "uXV8TAZEw36DkgW8Ak3MpSJs1ofBb3Smkc/6pZ29sCAN1KzCAQzsje4sUwugf+FVicrHvlamCOlFZIXgct+iqQ==";
      };
    };
    "esbuild-windows-32-0.14.42" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.14.42.tgz";
        sha512 = "4iw/8qWmRICWi9ZOnJJf9sYt6wmtp3hsN4TdI5NqgjfOkBVMxNdM9Vt3626G1Rda9ya2Q0hjQRD9W1o+m6Lz6g==";
      };
    };
    "esbuild-windows-64-0.14.42" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.14.42.tgz";
        sha512 = "j3cdK+Y3+a5H0wHKmLGTJcq0+/2mMBHPWkItR3vytp/aUGD/ua/t2BLdfBIzbNN9nLCRL9sywCRpOpFMx3CxzA==";
      };
    };
    "esbuild-windows-arm64-0.14.42" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.14.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.14.42.tgz";
        sha512 = "+lRAARnF+hf8J0mN27ujO+VbhPbDqJ8rCcJKye4y7YZLV6C4n3pTRThAb388k/zqF5uM0lS5O201u0OqoWSicw==";
      };
    };
    "fast-fuzzy-1.11.2" = {
      name = "fast-fuzzy";
      packageName = "fast-fuzzy";
      version = "1.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-fuzzy/-/fast-fuzzy-1.11.2.tgz";
        sha512 = "H1ct10Pzx+pSO4h7F1uBXET91ay2hy67J1aQZFKL23EXsOoanpwjPNQQoc+NhClKJMmlGGN+0bXhIdFJX70BJw==";
      };
    };
    "graphemesplit-2.4.4" = {
      name = "graphemesplit";
      packageName = "graphemesplit";
      version = "2.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphemesplit/-/graphemesplit-2.4.4.tgz";
        sha512 = "lKrpp1mk1NH26USxC/Asw4OHbhSQf5XfrWZ+CDv/dFVvd1j17kFgMotdJvOesmHkbFX9P9sBfpH8VogxOWLg8w==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "internmap-2.0.3" = {
      name = "internmap";
      packageName = "internmap";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internmap/-/internmap-2.0.3.tgz";
        sha512 = "5Hh7Y1wQbvY5ooGgPbDaL5iYLAPzMTUrjMulskHLH6wnv/A+1q5rgEaiuqEjB+oxGXIVZs1FF+R/KPN3ZSQYYg==";
      };
    };
    "js-base64-3.7.2" = {
      name = "js-base64";
      packageName = "js-base64";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-base64/-/js-base64-3.7.2.tgz";
        sha512 = "NnRs6dsyqUXejqk/yv2aiXlAvOs56sLkX6nUdeaNezI5LFFLlsZjOThmwnrcwh5ZZRwZlCMnVAY3CvhIhoVEKQ==";
      };
    };
    "katex-0.15.6" = {
      name = "katex";
      packageName = "katex";
      version = "0.15.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/katex/-/katex-0.15.6.tgz";
        sha512 = "UpzJy4yrnqnhXvRPhjEuLA4lcPn6eRngixW7Q3TJErjg3Aw2PuLFBzTkdUb89UtumxjhHTqL3a5GDGETMSwgJA==";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha1 = "f3f7522f4ef782348da8161bad9ecfd51bf83a75";
      };
    };
    "robust-predicates-3.0.1" = {
      name = "robust-predicates";
      packageName = "robust-predicates";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/robust-predicates/-/robust-predicates-3.0.1.tgz";
        sha512 = "ndEIpszUHiG4HtDsQLeIuMvRsDnn8c8rYStabochtUeCvfuvNptb5TUbVD68LRAILPX7p9nqQGh4xJgn3EHS/g==";
      };
    };
    "rw-1.3.3" = {
      name = "rw";
      packageName = "rw";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rw/-/rw-1.3.3.tgz";
        sha1 = "3f862dfa91ab766b14885ef4d01124bfda074fb4";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "tiny-inflate-1.0.3" = {
      name = "tiny-inflate";
      packageName = "tiny-inflate";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-inflate/-/tiny-inflate-1.0.3.tgz";
        sha512 = "pkY1fj1cKHb2seWDy0B16HeWyczlJA9/WW3u3c4z/NiWDsO3DOU5D7nhTLE9CF0yXv/QZFY7sEJmj24dK+Rrqw==";
      };
    };
    "typescript-4.7.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.7.2.tgz";
        sha512 = "Mamb1iX2FDUpcTRzltPxgWMKy3fhg0TN378ylbktPGPK/99KbDtMQ4W1hwgsbPAsG3a0xKa1vmw4VKZQbkvz5A==";
      };
    };
    "unicode-trie-2.0.0" = {
      name = "unicode-trie";
      packageName = "unicode-trie";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicode-trie/-/unicode-trie-2.0.0.tgz";
        sha512 = "x7bc76x0bm4prf1VLg79uhAzKw8DVboClSN5VxJuQ+LKDOVEW9CdH+VY7SP+vX7xCYQqzzgQpFqz15zeLvAtZQ==";
      };
    };
  };
  args = {
    name = "1lab";
    packageName = "1lab";
    version = "1.0.0";
    src = ../../..;
    dependencies = [
      sources."@types/d3-7.4.0"
      sources."@types/d3-array-3.0.3"
      sources."@types/d3-axis-3.0.1"
      sources."@types/d3-brush-3.0.1"
      sources."@types/d3-chord-3.0.1"
      sources."@types/d3-color-3.1.0"
      sources."@types/d3-contour-3.0.1"
      sources."@types/d3-delaunay-6.0.1"
      sources."@types/d3-dispatch-3.0.1"
      sources."@types/d3-drag-3.0.1"
      sources."@types/d3-dsv-3.0.0"
      sources."@types/d3-ease-3.0.0"
      sources."@types/d3-fetch-3.0.1"
      sources."@types/d3-force-3.0.3"
      sources."@types/d3-format-3.0.1"
      sources."@types/d3-geo-3.0.2"
      sources."@types/d3-hierarchy-3.1.0"
      sources."@types/d3-interpolate-3.0.1"
      sources."@types/d3-path-3.0.0"
      sources."@types/d3-polygon-3.0.0"
      sources."@types/d3-quadtree-3.0.2"
      sources."@types/d3-random-3.0.1"
      sources."@types/d3-scale-4.0.2"
      sources."@types/d3-scale-chromatic-3.0.0"
      sources."@types/d3-selection-3.0.2"
      sources."@types/d3-shape-3.1.0"
      sources."@types/d3-time-3.0.0"
      sources."@types/d3-time-format-4.0.0"
      sources."@types/d3-timer-3.0.0"
      sources."@types/d3-transition-3.0.1"
      sources."@types/d3-zoom-3.0.1"
      sources."@types/geojson-7946.0.8"
      sources."commander-7.2.0"
      sources."d3-7.4.4"
      sources."d3-array-3.1.6"
      sources."d3-axis-3.0.0"
      sources."d3-brush-3.0.0"
      sources."d3-chord-3.0.1"
      sources."d3-color-3.1.0"
      sources."d3-contour-3.0.1"
      sources."d3-delaunay-6.0.2"
      sources."d3-dispatch-3.0.1"
      sources."d3-drag-3.0.0"
      sources."d3-dsv-3.0.1"
      sources."d3-ease-3.0.1"
      sources."d3-fetch-3.0.1"
      sources."d3-force-3.0.0"
      sources."d3-format-3.1.0"
      sources."d3-geo-3.0.1"
      sources."d3-hierarchy-3.1.2"
      sources."d3-interpolate-3.0.1"
      sources."d3-path-3.0.1"
      sources."d3-polygon-3.0.1"
      sources."d3-quadtree-3.0.1"
      sources."d3-random-3.0.1"
      sources."d3-scale-4.0.2"
      sources."d3-scale-chromatic-3.0.0"
      sources."d3-selection-3.0.0"
      sources."d3-shape-3.1.0"
      sources."d3-time-3.0.0"
      sources."d3-time-format-4.1.0"
      sources."d3-timer-3.0.1"
      sources."d3-transition-3.0.1"
      sources."d3-zoom-3.0.0"
      sources."delaunator-5.0.0"
      sources."esbuild-0.14.42"
      sources."esbuild-android-64-0.14.42"
      sources."esbuild-android-arm64-0.14.42"
      sources."esbuild-darwin-64-0.14.42"
      sources."esbuild-darwin-arm64-0.14.42"
      sources."esbuild-freebsd-64-0.14.42"
      sources."esbuild-freebsd-arm64-0.14.42"
      sources."esbuild-linux-32-0.14.42"
      sources."esbuild-linux-64-0.14.42"
      sources."esbuild-linux-arm-0.14.42"
      sources."esbuild-linux-arm64-0.14.42"
      sources."esbuild-linux-mips64le-0.14.42"
      sources."esbuild-linux-ppc64le-0.14.42"
      sources."esbuild-linux-riscv64-0.14.42"
      sources."esbuild-linux-s390x-0.14.42"
      sources."esbuild-netbsd-64-0.14.42"
      sources."esbuild-openbsd-64-0.14.42"
      sources."esbuild-sunos-64-0.14.42"
      sources."esbuild-windows-32-0.14.42"
      sources."esbuild-windows-64-0.14.42"
      sources."esbuild-windows-arm64-0.14.42"
      sources."fast-fuzzy-1.11.2"
      sources."graphemesplit-2.4.4"
      sources."iconv-lite-0.6.3"
      sources."internmap-2.0.3"
      sources."js-base64-3.7.2"
      (sources."katex-0.15.6" // {
        dependencies = [
          sources."commander-8.3.0"
        ];
      })
      sources."pako-0.2.9"
      sources."robust-predicates-3.0.1"
      sources."rw-1.3.3"
      sources."safer-buffer-2.1.2"
      sources."tiny-inflate-1.0.3"
      sources."typescript-4.7.2"
      sources."unicode-trie-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = " A formalised, cross-linked reference resource for mathematics done in Homotopy Type Theory ";
      homepage = "https://github.com/plt-amy/1lab#readme";
      license = "AGPL-3.0";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
